### ISSUE TITLE
Exempt /announce from the spam command restriction

### ISSUE THREAD

**Issue by skylardarkfox** [alexradu04/tsuBot#3]
/announce is a new command added this month (exclusively for mods) that adds a stylized frame around the following message. This command seems like it would be very handy for especially this purpose. There are also colored alternatives: /announceblue, /announcegreen, /announceorange, and /announcepurple.

**Comment by alexradu04** [comment]
Added this in the last commit. Thanks for letting me know. Also, color-specific announcements won't work, as bots can't use them yet. This seems to be a known issue by twitch, so I guess we'll have to wait for an update from them regarding this.
